<?php
declare(strict_types=1);

namespace App\Controller;
use Dompdf\Dompdf;

/**
 * ParteSalidas Controller
 *
 * @property \App\Model\Table\ParteSalidasTable $ParteSalidas
 * @method \App\Model\Entity\ParteSalida[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ParteSalidasController extends AppController
{
    protected $ParteSalidaRegistros = null;

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->ParteSalidaRegistros = $this->fetchTable('ParteSalidaRegistros');
        $this->loadComponent("StockManager", ['usuario' => $this->usuario_sesion]);

    }
    public function beforeRender(\Cake\Event\EventInterface $event) {
        parent::beforeRender($event);
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $opt_fec_inicio = $this->request->getQuery('fec_inicio');
        $opt_fec_fin = $this->request->getQuery('fec_fin');

        $parte_salidas = $this->ParteSalidas
            ->find()
            ->contain(['Usuarios'])
            ->orderBy(['ParteSalidas.created'=>'DESC'])
        ;
        if(!isset($opt_fec_inicio)){
            $opt_fec_inicio = date("Y-m-d",strtotime("-7 day"));
        }
        if(!isset($opt_fec_fin)){
            $opt_fec_fin = date("Y-m-d");
        }
       
        if(isset($opt_fec_inicio) && $opt_fec_inicio != ''){
            $parte_salidas = $parte_salidas->andWhere(['ParteSalidas.fecha_emision >=' => $opt_fec_inicio]);
        }
        if(isset($opt_fec_fin) && $opt_fec_fin != ''){
            $parte_salidas = $parte_salidas->andWhere(['ParteSalidas.fecha_emision <=' => $opt_fec_fin]);
        }



        $parteSalidas = $this->paginate( $parte_salidas);
        $top_links = [];
        $top_links['links'] = [];
        $top_links['title'] = "Salidas";

        $top_links['links']['btnNuevo'] = [
            'name' => '<i class="fa fa-fw fa-plus"></i> Registrar Salidas',
            'params' => [
                'action' => 'add'
            ],
        ];


        $this->set("view_title", "Salidas");
        $this->set("top_links", $top_links);

        $this->set(compact('parteSalidas'));
        $this->set(compact('opt_fec_inicio','opt_fec_fin'));
    }

    /**
     * View method
     *
     * @param string|null $id Parte Salida id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $parteSalida = $this->ParteSalidas->get($id, [
            'contain' => [ 'Usuarios', 'ParteEntradas', 'ParteSalidaRegistros' => ['Items']],
        ]);
        $top_links = [];
        $top_links['links'] = [];
        $top_links['title'] = "Detalle Salida";

        $top_links['links']['btnRegresar'] = [
            'name' => '<i class="fa fa-fw fa-chevron-left"></i> Listado',
            'params' => [
                'action' => 'index'
            ],
        ];


        $this->set("view_title", "Detalle Salida");
        $this->set("top_links", $top_links);
        $this->set(compact('parteSalida'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $parteSalida = $this->ParteSalidas->newEmptyEntity();
        if ($this->request->is('post')) {
            $data = $this->request->getData();
            $parteSalida = $this->ParteSalidas->patchEntity($parteSalida, $data);
            $parteSalida->usuario_id = $this->usuario_sesion['id'];
            $parteSalida = $this->ParteSalidas->save($parteSalida);
            if($parteSalida){
                $registros = json_decode( $this->request->getData('items_registros'), true);
                foreach($registros as $k => $reg){
                    $parte_salida_registros = $this->ParteSalidaRegistros->newEmptyEntity();
                    $parte_salida_registros->parte_salida_id = $parteSalida->id;
                    $parte_salida_registros->item_index = $k+1;
                    $parte_salida_registros->item_id = $reg['id'];
                    $parte_salida_registros->cantidad = $reg['cantidad'];
                    $parte_salida_registros = $this->ParteSalidaRegistros->save($parte_salida_registros);
                    if($parte_salida_registros){
                        $this->StockManager->retirarStock(
                            $reg['id'],
                            $reg['cantidad'],
                            "PARTE_SALIDA"
                        );
                    }

                }
            }
            if ($parteSalida) {
                $this->Flash->success(__('Parte de salida guardado.'));
                if($this->request->getData('imprimir') == 'imprimir'){
                    return $this->redirect(['action' => 'procesar' , $parteSalida->id]);
                }
                return $this->redirect(['action' => 'index' ]);
            }
            $this->Flash->error(__('Ocurrio un error, intente de nuevo.'));
        }
        $usuarios = $this->ParteSalidas->Usuarios->find('list', ['limit' => 200]);


        $top_links = [];
        $top_links['links'] = [];
        $top_links['title'] = "Nueva Salida";

        $top_links['links']['btnRegresar'] = [
            'name' => '<i class="fa fa-fw fa-chevron-left"></i> Listado',
            'params' => [
                'action' => 'index'
            ],
        ];


        $this->set("view_title", "Nueva Salida");
        $this->set("top_links", $top_links);
        $this->set(compact('parteSalida','usuarios'));
    }


    /**
     * Delete method
     *
     * @param string|null $id Parte Salida id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $parte_salida= $this->ParteSalidas->find()
        ->where(['id' => $id])
        ->contain(['ParteSalidaRegistros'])
        ->first();

        if ($this->ParteSalidas->delete($parte_salida)) {
            foreach($parte_salida->parte_salida_registros as $registro){
                $del_reg = $this->ParteSalidaRegistros->delete($registro);
                if($del_reg){
                    $this->StockManager->ingresarStock(
                        $registro->item_id,
                        $registro->cantidad,
                        "PARTE_SALIDA_ELIMINAR_REGISTRO"
                    );
                }
            }
            $this->Flash->success(__('Registro eliminado.'));
        } else {
            $this->Flash->error(__('Ocurrió un error. Intente de nuevo.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function imprimirPdf($id , $guardar = false){

        ini_set('memory_limit', '-1');

        $parteSalida = $this->ParteSalidas
        ->find()->where(['ParteSalidas.id' => $id])
        ->contain([ 'Usuarios','ParteSalidaRegistros' => ['Items']])->first();

        if($parteSalida){
            $this->viewBuilder()->setClassName(null);
            $this->viewBuilder()->setLayout("none");
            $logo = $this->getConfig('global_logo');
            $this->viewBuilder()->setVars([
                'parte_salida'        => $parteSalida,
                'logo'                => WWW_ROOT. $logo,
                'empresa'             => $this->datos_empresa
            ]);
            $html = $this->render("/ParteSalidas/imprimir_pdf");

            $dompdf = new Dompdf();

            $options = $dompdf->getOptions();

            // para que se reconozca la ruta base
            $dompdf->getOptions()->setChroot(ROOT);


            $options->set('default_font', 'Helvetica');
            //$options->set('isRemoteEnabled', true);
            $dompdf->setOptions($options);

            $dompdf->loadHtml($html);
            $dompdf->setPaper("A4");
            $dompdf->render();
            if(!$guardar){
                $dompdf->stream("Parte_salida_{$parteSalida->id}.pdf", ['Attachment' => false]);
            }else{
                $output = $dompdf->output();
                file_put_contents( WWW_ROOT . "parte_salida.pdf", $output);
                return 'parte_salida.pdf';
            }
        }else{
            $this->Flash->error(__('Parte de Salida no encontrado.'));
        }
        return $this->redirect(['action' => 'index']);
    }


    public function procesar($id = null)
    {
        $parte_salida = $this->ParteSalidas->find()->where(['id' => $id])->first();
        if(!$parte_salida){
            $this->Flash->error(__('No se encontro el parte de salida'));
            return $this->redirect(['action' => 'index']);
        }

        if ($this->request->is('post')) {
            $nombre_pdf = $this->imprimirPdf($id, true);
            if($nombre_pdf){
                if($this->request->getData("btn_correo")){
                    $correo = $this->request->getData('correo');
                    $this->emailCtrl->enviarParte($correo, $nombre_pdf, 'PDF Parte Salida');
                    $this->Flash->success(__('Se envió el correo.'));
                }elseif($this->request->getData("btn_whatsapp")){
                    $whatsapp_cel = $this->request->getData('celular');
                    if($whatsapp_cel != ''){
                        $num = $this->whastapp_ctrl->verfNumero($whatsapp_cel);
                        $finfo= new \finfo(FILEINFO_MIME_TYPE);
                        $mimetype = $finfo->file($nombre_pdf);
                        $nuevadata = ['number'=> $num, 'file'=> curl_file_create($nombre_pdf, $mimetype, $nombre_pdf )];
                        $url = $this->whastapp_ctrl->get_url_file() . "?token=" . $this->whastapp_ctrl->get_token();
                        $this->whastapp_ctrl->curl($url, $nuevadata);
                        $this->Flash->success(__('Se envio el mensaje whatsapp.'));
                    }
                }
            }else{
                $this->Flash->error(__('Ocurrio un error.'));
            }
        }

        $top_links = [
            'title' => 'Procesar Parte Salida',
            'links' =>  [
                'btn' => [
                    'name' => '<i class="fas fa-chevron-left"></i> Regresar al Listado ',
                    'params'=>[
                        'controller' => 'parte-salidas',
                        'action' => 'index'
                    ]
                ]
            ]
        ];

        $this->set(compact('top_links'));
        $this->set('view_title', 'Procesar Parte Salida');
        $this->set('parte_salida', $parte_salida);
    }

    //Se usa en mover mercaderia, recibe el data y guarda con la data enviada
    public function saveSalida($data = []){
        $parte_salida = $this->ParteSalidas->newEmptyEntity();
        $parte_salida = $this->ParteSalidas->patchEntity($parte_salida, $data);
        return $this->ParteSalidas->save($parte_salida);
    }

    public function enviarAdjunto($id,$tipo_mensaje){
        try {
            $respuesta = [
                'success' => false,
                'data' => '',
                'message' => 'No se enviaron datos',
            ];

            $data = $this->request->getData();
            if ($this->request->is('post')) {
                $nombre_pdf = $this->imprimirPdf($id, true);
                if($nombre_pdf){
                    if($this->request->getData("btn_correo")){
                        $correo = $this->request->getData('correo');
                        if($this->emailCtrl->enviarParte($correo, $nombre_pdf, 'PDF Parte Salida')){
                            $respuesta = [
                                'success' => false,
                                'data' => '',
                                'message' => 'Se envio el correo',
                            ];
                        }
                    }elseif($this->request->getData("btn_whatsapp")){
                        $whatsapp_cel = $this->request->getData('whatsapp');
                        if($whatsapp_cel != ''){
                            $num = $this->whastapp_ctrl->verfNumero($whatsapp_cel);
                            $finfo= new \finfo(FILEINFO_MIME_TYPE);
                            $mimetype = $finfo->file($nombre_pdf);
                            $nuevadata = ['number'=> $num, 'file'=> curl_file_create($nombre_pdf, $mimetype, $nombre_pdf )];
                            $url = $this->whastapp_ctrl->get_url_file() . "?token=" . $this->whastapp_ctrl->get_token();
                            $this->whastapp_ctrl->curl($url, $nuevadata);
                            $respuesta = [
                                'success' => false,
                                'data' => '',
                                'message' => 'Se envio el whatsapp',
                            ];
                        }else{
                            $respuesta = [
                                'success' => false,
                                'data' => '',
                                'message' => 'Numero de Whatsapp no valido',
                            ];
                        }
                    }
                }else{
                    $respuesta = [
                        'success' => false,
                        'data' => '',
                        'message' => 'Este parte no existe',
                    ];
                }
            }
        }  catch (\Throwable $e) {
            $respuesta = [
                'success' => false,
                'data' => '',
                'message' => 'ERROR: '.$e->getMessage(),
            ];
        }

        return $this->response->withType('application/json')->withStringBody(json_encode($respuesta));
    }
}
