<?php
declare(strict_types=1);

namespace App\Controller;
use Dompdf\Dompdf;
/**
 * ParteEntradas Controller
 *
 * @property \App\Model\Table\ParteEntradasTable $ParteEntradas
 * @method \App\Model\Entity\ParteEntrada[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ParteEntradasController extends AppController
{
    private $ParteEntradaRegistros = null;
    private $ParteSalidas = null;
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->ParteEntradaRegistros = $this->fetchTable('ParteEntradaRegistros');
        $this->ParteSalidas = $this->fetchTable('ParteSalidas');
        $this->loadComponent("StockManager", ['usuario' => $this->usuario_sesion]);
    }
    public function beforeRender(\Cake\Event\EventInterface $event) {
        parent::beforeRender($event);
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $opt_fec_inicio = $this->request->getQuery('fec_inicio');
        $opt_fec_fin = $this->request->getQuery('fec_fin');

        $parte_entradas = $this->ParteEntradas->find()->contain(['ParteSalidas', 'Usuarios'])->orderBy(['ParteEntradas.id' => "DESC"]);
        if(!isset($opt_fec_inicio)){
            $opt_fec_inicio = date("Y-m-d",strtotime("-7 day"));
        }
        if(!isset($opt_fec_fin)){
            $opt_fec_fin = date("Y-m-d");
        }

        if(isset($opt_fec_inicio) && $opt_fec_inicio != ''){
            $parte_entradas = $parte_entradas->andWhere(['ParteEntradas.fecha >=' => $opt_fec_inicio]);
        }
        if(isset($opt_fec_fin) && $opt_fec_fin != ''){
            $parte_entradas = $parte_entradas->andWhere(['ParteEntradas.fecha <=' => $opt_fec_fin]);
        }

        $parteEntradas = $this->paginate($parte_entradas , ['maxLimit' => 20]);
        $top_links = [];
        $top_links['links'] = [];
        $top_links['title'] = "Ingresos";

        $top_links['links']['btnNuevo'] = [
            'name' => '<i class="fa fa-fw fa-plus"></i> Registrar Ingresos',
            'params' => [
                'action' => 'add'
            ],
        ];


        $this->set(compact('opt_fec_inicio','opt_fec_fin'));
        $this->set(compact('parteEntradas'));
        $this->set("view_title", "Ingresos");
        $this->set("top_links", $top_links);

    }

    /**
     * View method
     *
     * @param string|null $id Parte Entrada id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $parteEntrada = $this->ParteEntradas->get($id, [
            'contain' => ['ParteSalidas',  'Usuarios', 'ParteEntradaRegistros' => ['Items']],
        ]);

        $top_links = [];
        $top_links['links'] = [];
        $top_links['title'] = "Detalle Ingreso";

        $top_links['links']['btnNuevo'] = [
            'name' => '<i class="fa fa-fw fa-chevron-left"></i> Listado',
            'params' => [
                'action' => 'index'
            ],
        ];


        $this->set("view_title", "Detalle Ingreso");
        $this->set("top_links", $top_links);


        $this->set(compact('parteEntrada'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $flag_ps = $this->request->getQuery('ps');
        if($flag_ps == true){
            $parte_salida_id = $this->request->getQuery('psid');
            $parte_salida = $this->ParteSalidas->find()->where(['id' => $parte_salida_id])->contain(['ParteSalidaRegistros' => 'Items'])->first();
        }else{
            $flag_ps = false;
            $parte_salida = null;
        }

        $parteEntrada = $this->ParteEntradas->newEmptyEntity();

        if ($this->request->is('post')) {
            $data = $this->request->getData();
            $parteEntrada = $this->ParteEntradas->patchEntity($parteEntrada, $data);

            $parteEntrada->fecha = isset($data['fecha']) ? $data['fecha'] : null;
            $parteEntrada->usuario_id = $this->usuario_sesion['id'];
            if($flag_ps == true && $parte_salida){
                $parteEntrada->parte_salida_id = $parte_salida->id;
            }
            $parteEntrada = $this->ParteEntradas->save($parteEntrada);
            if($parteEntrada){
                $registros = json_decode( $this->request->getData('items_registros'), true);

                $array_registros = [];
                foreach($registros as $k => $reg){
                    $parte_entrada_registros = $this->ParteEntradaRegistros->newEmptyEntity();
                    $parte_entrada_registros->parte_entrada_id = $parteEntrada->id;
                    $parte_entrada_registros->item_index = $k+1;
                    $parte_entrada_registros->item_id = $reg['id'];
                    $parte_entrada_registros->cantidad = $reg['cantidad'];
                    $parte_entrada_registros = $this->ParteEntradaRegistros->save($parte_entrada_registros);
                    if($parte_entrada_registros){
                        $ingresar_stock = $this->StockManager->ingresarStock(
                            $reg['id'],
                            $reg['cantidad'],
                            "PARTE_ENTRADA"
                        );
                    }
                    $array_registros [] = $parte_entrada_registros;
                }
            }
            if ($parteEntrada) {
                $this->Flash->success(__('Parte de entrada guardado.'));
                if($this->request->getData('imprimir') == 'imprimir'){
                    return $this->redirect(['action' => 'procesar' , $parteEntrada->id]);
                }
                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Ocurrio un error, intente de nuevo.'));
        }
        $parteSalidas = $this->ParteEntradas->ParteSalidas->find('list', ['limit' => 200]);

        $top_links = [];
        $top_links['links'] = [];
        $top_links['title'] = "Nuevo Ingreso";

        $top_links['links']['btnNuevo'] = [
            'name' => '<i class="fa fa-fw fa-chevron-left"></i> Listado',
            'params' => [
                'action' => 'index'
            ],
        ];


        $this->set("view_title", "Nuevo Ingreso");
        $this->set("top_links", $top_links);

        $this->set('flag_ps', $flag_ps);
        $this->set('parte_salida', $parte_salida);

        $this->set(compact('parteEntrada', 'parteSalidas'));
    }

      /**
     * Delete method
     *
     * @param string|null $id Parte Entrada id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $parteEntrada = $this->ParteEntradas->find()
        ->where(['id' => $id])
        ->contain(['ParteEntradaRegistros'])
        ->first();

        if ($this->ParteEntradas->delete($parteEntrada)) {
            foreach($parteEntrada->parte_entrada_registros as $registro){
                $del_reg = $this->ParteEntradaRegistros->delete($registro);
                if($del_reg){
                    $retirar_stock = $this->StockManager->retirarStock(
                        $registro->item_id,
                        $registro->cantidad,
                        "PARTE_ENTRADA_ELIMINAR_REGISTRO"
                    );
                }
            }
            $this->Flash->success(__('Registro eliminado.'));
        } else {
            $this->Flash->error(__('Ocurrió un error. Intente de nuevo.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function imprimirPdf($id,$guardar = false){

        ini_set('memory_limit', '-1');

        $parte_entrada = $this->ParteEntradas
        ->find()->where(['ParteEntradas.id' => $id])
        ->contain(['Usuarios','ParteEntradaRegistros' => ['Items']])->first();

        if($parte_entrada){

            $this->viewBuilder()->setClassName(null);
            $this->viewBuilder()->setLayout("none");
            $logo = $this->getConfig('global_logo');
            $this->viewBuilder()->setVars([
                'parte_entrada'        => $parte_entrada,
                'logo'                => WWW_ROOT. $logo
            ]);
            $html = $this->render("/ParteEntradas/imprimir_pdf");

            $dompdf = new Dompdf();

            $options = $dompdf->getOptions();

            // para que se reconozca la ruta base
            $dompdf->getOptions()->setChroot(ROOT);


            $options->set('default_font', 'Helvetica');
            //$options->set('isRemoteEnabled', true);
            $dompdf->setOptions($options);

            $dompdf->loadHtml($html);
            $dompdf->setPaper("A4");
            $dompdf->render();

            if(!$guardar){
                $dompdf->stream("Parte_entrada_{$parte_entrada->id}.pdf", ['Attachment' => false]);
            }else{
                $output = $dompdf->output();
                file_put_contents( WWW_ROOT . "parte_entrada.pdf", $output);
                return 'parte_entrada.pdf';
            }
        }else{
            $this->Flash->error(__('Parte de Entrada no encontrado.'));
        }
        return $this->redirect(['action' => 'index']);
    }

    public function procesar($id = null)
    {
        $parte_entrada = $this->ParteEntradas->find()->where(['id' => $id])->first();
        if(!$parte_entrada){
            $this->Flash->error(__('No se encontro el parte de entrada'));
            return $this->redirect(['action' => 'index']);
        }

        if ($this->request->is('post')) {
            $nombre_pdf = $this->imprimirPdf($id, true);
            if($nombre_pdf){
                if($this->request->getData("btn_correo")){
                    $correo = $this->request->getData('correo');
                    $this->emailCtrl->enviarParte($correo, $nombre_pdf, 'PDF Parte Entrada');
                    $this->Flash->success(__('Se envió el correo.'));
                }elseif($this->request->getData("btn_whatsapp")){
                    $whatsapp_cel = $this->request->getData('celular');
                    if($whatsapp_cel != ''){
                        $num = $this->whastapp_ctrl->verfNumero($whatsapp_cel);
                        $finfo= new \finfo(FILEINFO_MIME_TYPE);
                        $mimetype = $finfo->file($nombre_pdf);
                        $nuevadata = ['number'=> $num, 'file'=> curl_file_create($nombre_pdf, $mimetype, $nombre_pdf )];
                        $url = $this->whastapp_ctrl->get_url_file() . "?token=" . $this->whastapp_ctrl->get_token();
                        $this->whastapp_ctrl->curl($url, $nuevadata);
                    }
                    $this->Flash->success(__('Se envio el mensaje whatsapp.'));
                }
            }else{
                $this->Flash->error(__('Ocurrio un error.'));
            }
        }

        $top_links = [
            'title' => 'Procesar Parte Entrada',
            'links' =>  [
                'btn' => [
                    'name' => '<i class="fas fa-chevron-left"></i> Regresar al Listado ',
                    'params'=>[
                        'controller' => 'parte-entradas',
                        'action' => 'index'
                    ]
                ]
            ]
        ];

        $this->set(compact('top_links'));
        $this->set('view_title', 'Procesar Parte Entrada');
        $this->set('parte_entrada', $parte_entrada);
    }

    //Se usa en mover mercaderia, recibe el data y guarda con la data enviada
    public function saveEntrada($data = []){
        $parte_entrada = $this->ParteEntradas->newEmptyEntity();
        $parte_entrada = $this->ParteEntradas->patchEntity($parte_entrada, $data);
        return $this->ParteEntradas->save($parte_entrada);
    }

    /**
     * @param $id
     * @param $tipo_mensaje 1 para ws, y 2 para correo
     * @return \Cake\Http\Response
     */
    public function enviarAdjunto($id,$tipo_mensaje){
        try {
            $respuesta = [
                'success' => false,
                'data' => '',
                'message' => 'No se enviaron datos',
            ];

            $data = $this->request->getData();
            if ($this->request->is('post')) {
                $nombre_pdf = $this->imprimirPdf($id, true);
                if($nombre_pdf){
                    if($tipo_mensaje == '2'){
                        $correo = $this->request->getData('correo');
                        if(true){
                            $respuesta = [
                                'success' => true,
                                'data' => $this->emailCtrl->enviarParte($correo, $nombre_pdf, 'PDF Parte Entrada'),
                                'message' => 'Se envio el correo',
                            ];
                        }
                    }elseif($tipo_mensaje == '1'){
                        $whatsapp_cel = $this->request->getData('celular');
                        if($whatsapp_cel != ''){
                            $num = $this->whastapp_ctrl->verfNumero($whatsapp_cel);
                            $finfo= new \finfo(FILEINFO_MIME_TYPE);
                            $mimetype = $finfo->file($nombre_pdf);
                            $nuevadata = ['number'=> $num, 'file'=> curl_file_create($nombre_pdf, $mimetype, $nombre_pdf )];
                            $url = $this->whastapp_ctrl->get_url_file() . "?token=" . $this->whastapp_ctrl->get_token();
                            $this->whastapp_ctrl->curl($url, $nuevadata);
                            $respuesta = [
                                'success' => false,
                                'data' => '',
                                'message' => 'Se envio el whatsapp',
                            ];
                        }else{
                            $respuesta = [
                                'success' => false,
                                'data' => '',
                                'message' => 'Numero de Whatsapp no valido',
                            ];
                        }
                    }
                }else{
                    $respuesta = [
                        'success' => false,
                        'data' => '',
                        'message' => 'Este parte no existe',
                    ];
                }
            }
        }  catch (\Throwable $e) {
            $respuesta = [
                'success' => false,
                'data' => '',
                'message' => 'ERROR: '.$e->getMessage(),
            ];
        }

        return $this->response->withType('application/json')->withStringBody(json_encode($respuesta));
    }
}
