<?php
declare(strict_types=1);

namespace App\Controller;
use App\Controller\AppController;
use Cake\Event\EventInterface;

class SuperadminController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function initialize():void {
        parent::initialize();
    }

    public function beforeFilter(EventInterface $event)
    {
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        $this->set("view_title", "Superadministrador");
    }


}
