<?php
declare(strict_types=1);

namespace App\Controller;

/**
 * Web Controller
 *
 */
class WebController extends AppController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Authentication->allowUnauthenticated(['consultaCpe']);
    }
    public function index(){
        return $this->redirect(['controller' => 'Ventas']);
    }
    public function intranet(){
        return $this->redirect(['controller' => 'Ventas']);
    }
}
