<?php

namespace App\Controller\Component;

use App\Model\Entity\Stock;
use App\Model\Entity\StockHistorial;
use Cake\Controller\Component;
use Cake\Http\ServerRequest;
use Cake\ORM\Table;
use Cake\ORM\TableRegistry;
use phpDocumentor\Reflection\Types\Integer;


class StockManagerComponent extends Component
{

    private $ModelStock;
    private $ModelStockHistorial;
    private $ModelItems;
    private $ModelItemRels;


    private $usuario;
    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        $this->usuario = isset($config['usuario'])?$config['usuario']: [] ;
        $this->ModelStockHistorial = TableRegistry::getTableLocator()->get("StockHistorial");
        $this->ModelStock = TableRegistry::getTableLocator()->get("Stock");
        $this->ModelItems = TableRegistry::getTableLocator()->get("Items");
        $this->ModelItemRels = TableRegistry::getTableLocator()->get("ItemRels");

    }

    /**
     * @param int $item_id Id del Item
     * @param int $cantidad Cantidad del producto a retirar
     * @param string $operacion AJUSTE_MANUAL, VENTA,COMPRA,ANULACION_VENTA, ETC
     * @param string $comentario Descripcion del movimiento
     * @param array $documento Array con formato = [tipo => {documento_tipo} ,codigo=>{serie}-{correlativo} ]
     * @return Stock
     */
    public function retirarStock($item_id, $cantidad, $operacion='', $comentario='',$documento=[] )
    {
        $st = $this->ModelStock->find()->where(['item_id' => $item_id])->first();
        $item= $this->ModelItems->find()->where(['id'=>$item_id])->first() ;

        /**
         * Comprobamos que este habilitado
         * el control de stock
         */
        if($item && $item->unidad != 'ZZ'){
            if($item->controlar_inventario ==1){
                /**
                 * Actualizamos el registro en la tabla Stock
                 * Si el registro no existe lo creamos
                 */
                if(!$st){
                    $st = new Stock();
                    $st->item_id = $item_id;
                    $st->stock = -$cantidad;
                } else {
                    $st->stock -= $cantidad;
                }
                $this->ModelStock->save($st);

                /**
                 * Procedemos a registrar el historial de stock
                 */

                $stock_hist = $this->ModelStockHistorial->newEmptyEntity();
                /**
                 * Informacion referente al Item
                 */
                $stock_hist->item_id = $item->id;
                $stock_hist->item_codigo = $item->codigo;
                $stock_hist->item_nombre = $item->nombre;
                $stock_hist->cantidad = -$cantidad;

                /**
                 * Datos del usuario
                 */
                $stock_hist->usuario_id = $this->usuario->id;
                /**
                 * Descripcion del movimiento
                 */
                $stock_hist->operacion = $operacion;
                $stock_hist->comentario = $comentario;
                /**
                 * Datos del documento relacionado
                 */
                $stock_hist->documento_tipo =  isset($documento['tipo']) ? $documento['tipo'] : ''  ;
                $stock_hist->documento_relacionado = isset($documento['codigo']) ? $documento['codigo'] : '';

                $this->ModelStockHistorial->save($stock_hist);
                return $st;
            }
        }elseif($item && $item->unidad === 'ZZ'){
            $serv_items = $this->ModelItemRels->find()->where(['item_id'=> $item->id]);
            $stock_array = [];
            foreach($serv_items as $serv_item)
            {
               $stock_array[] = $this->retirarStock($serv_item->item2_id,$serv_item->cantidad,$operacion,$comentario,$documento);
            }
            return $stock_array;
        }
        return false;


    }

    /**
     * @param int $item_id
     * @param int $cantidad
     * @param string $operacion
     * @param string $comentario
     * @param array $documento
     * @return Stock
     */
    public function ingresarStock($item_id,  $cantidad, $operacion='', $comentario='',$documento=[] )
    {
        $st = $this->ModelStock->find()->where(['item_id' => $item_id])->first();
        $item= $this->ModelItems->find()->where(['id'=>$item_id])->first() ;

        /**
         * Comprobamos que este habilitado
         * el control de stock
         */
        if($item && $item->unidad != 'ZZ'){
            if($item->controlar_inventario ==1){
                /**
                 * Actualizamos el registro en la tabla Stock
                 * Si el registro no existe lo creamos
                 */
                if(!$st){
                    $st = new Stock();
                    $st->item_id = $item_id;
                    $st->stock = $cantidad;
                } else {
                    $st->stock += $cantidad;
                }
                $this->ModelStock->save($st);

                /**
                 * Procedemos a registrar el historial de stock
                 */

                $stock_hist = $this->ModelStockHistorial->newEmptyEntity();
                /**
                 * Informacion referente al Item
                 */
                $stock_hist->item_id = $item->id;
                $stock_hist->item_codigo = $item->codigo;
                $stock_hist->item_nombre = $item->nombre;
                $stock_hist->cantidad = $cantidad;

                /**
                 * Datos del usuario
                 */
                $stock_hist->usuario_id = $this->usuario->id;
                /**
                 * Descripcion del movimiento
                 */
                $stock_hist->operacion = $operacion;
                $stock_hist->comentario = $comentario;
                /**
                 * Datos del documento relacionado
                 */
                $stock_hist->documento_tipo =  isset($documento['tipo']) ? $documento['tipo'] : ''  ;
                $stock_hist->documento_relacionado = isset($documento['codigo']) ? $documento['codigo'] : '';

                $this->ModelStockHistorial->save($stock_hist);
            }

            return $st;
        }elseif($item && $item->unidad === 'ZZ'){
            $serv_items = $this->ModelItemRels->find()->where(['item_id'=> $item->id]);
            $stock_array = [];
            foreach($serv_items as $serv_item)
            {
                $stock_array[] = $this->ingresarStock($serv_item->item2_id,$serv_item->cantidad,$operacion,$comentario,$documento);
            }
            return $stock_array;
        }
        return false;
    }

    /**
     * Recupera el stock de un producto
     * @param int $producto_id
     * @param false $getObj
     * @return int|null
     */
    public function getStock($producto_id, $getObj = false){
        $st = $this->ModelStock->find("all")
            ->andWhere(['item_id' => $producto_id])
            ->first();
        if($getObj){
            return (!$st) ? null : $st;
        }else{
            return (!$st) ? 0 : $st->stock;
        }
    }





}
